### ISSUE TITLE
pybullet.error: Not connected to physics server.

### ISSUE THREAD

**Issue by s2dk012** [moribots/minitaur_from_scratch#17]
when I run the python spot_ars.py I get the Not connected to physics server error

**Comment by moribots** [comment]
Have you tried running pybullet on its own? It sounds like you may have a bad installation

**Comment by dexfrost89** [comment]
Hello! I have the same problem when I try to run spot_ars.py. spot_ars_eval.py works fine.

**Comment by coheonsb** [comment]
Me too....

**Comment by treetwo77** [comment]
pybullet build time: Aug 24 2023 13:51:38
C:\Users\treetwo\Documents\spot_mini\spot_bullet\src\../..\spotmicro\util\pybullet_data
Process Process-14:
Traceback (most recent call last):
  File "C:\Users\treetwo\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\treetwo\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\treetwo\Documents\spot_mini\spot_bullet\src\ars_lib\ars.py", line 63, in ParallelWorker
    _ = env.reset()
  File "C:\Users\treetwo\Documents\spot_mini\spot_bullet\src\../..\spotmicro\spot_gym_env.py", line 312, in reset
    self._pybullet_client.configureDebugVisualizer(
pybullet.error: Not connected to physics server.
pybullet build time: Aug 24 2023 13:51:38
C:\Users\treetwo\Documents\spot_mini\spot_bullet\src\../..\spotmicro\util\pybullet_data
Process Process-15:
Traceback (most recent call last):
  File "C:\Users\treetwo\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\treetwo\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\treetwo\Documents\spot_mini\spot_bullet\src\ars_lib\ars.py", line 63, in ParallelWorker
    _ = env.reset()
  File "C:\Users\treetwo\Documents\spot_mini\spot_bullet\src\../..\spotmicro\spot_gym_env.py", line 312, in reset
    self._pybullet_client.configureDebugVisualizer(
pybullet.error: Not connected to physics server.


I also have this problem The problem doesn't get better even if you try to change the version
I really want to complete my custom robot.

**Comment by pickleCucumber** [comment]
If this problem is still relevant for someone, then I hope this helps someone.
The problem is related to the OS: on Windows, spawn is used instead of fork, so Python creates a new client connection to pybullet, but accesses it using the old ID instead of copying the process together with the connection.
The script runs parallel training by default, and the simplest solution in spot_ars.py is to remove multiprocessing and switch to normal training (comment out line 172, uncomment line 174), but since that is too simplistic, I propose a solution with the ability to choose the training mode (single/parallel). Now multiprocessing works by creating a local environment, local connection, local normalizer, and we pass arguments not via Pipe, then we synchronize.
P.S. spot_bezier_env.py -> spot_mini_mini/spotmicro/GymEnvs
ars1.py -> spot_mini_mini/spot_bullet/src/ars_lib/
spot_ars_hybrid.py  is analog  spot_ars.py

[spot_bezier_env.py](https://github.com/user-attachments/files/26053632/spot_bezier_env.py)

[spot_ars_hybrid.py](https://github.com/user-attachments/files/26053540/spot_ars_hybrid.py)

[ars1.py](https://github.com/user-attachments/files/26053601/ars1.py)

**Comment by pickleCucumber** [comment]
Actually it is enough to use Linux OS or a subsystem.
