### ISSUE TITLE
roslaunch mini_ros spot_move.launch exit code 127

### ISSUE THREAD

**Issue by JonathanMortes** [moribots/minitaur_from_scratch#21]
**Describe the bug**
The launching of the node doesn't do anything

**To Reproduce**
1. Get everything ready (roscore, joy node)
2.roslaunch mini_ros spot_move.launch
3. Nothing happens and the error pops out

**Expected behavior**
Control robot in simulator with joystick controller

**Screenshots**
jon@jon-noetic:~/catkin_ws$ roslaunch mini_ros spot_move.launch 
... logging to /home/jon/.ros/log/4d0e42a6-cde7-11eb-8559-f11a37245d28/roslaunch-jon-noetic-17165.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://jon-noetic:38909/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /spot_joy/deadzone: 0.05
 * /spot_joy/dev: /dev/input/js0
 * /spot_sm/frequency: 200.0
 * /spot_teleop/axis_angular: 0
 * /spot_teleop/axis_linear_x: 4
 * /spot_teleop/axis_linear_y: 3
 * /spot_teleop/axis_linear_z: 1
 * /spot_teleop/button_estop: 1
 * /spot_teleop/button_switch: 0
 * /spot_teleop/frequency: 200.0
 * /spot_teleop/scale_angular: 1.0
 * /spot_teleop/scale_linear: 1.0

NODES
  /
    spot_joy (joy/joy_node)
    spot_pybullet (mini_ros/spot_pybullet_interface)
    spot_sm (mini_ros/spot_sm)
    spot_teleop (mini_ros/teleop_node)

ROS_MASTER_URI=http://localhost:11311

process[spot_sm-1]: started with pid [17179]
process[spot_joy-2]: started with pid [17180]
[ INFO] [1623770031.194453852]: STARTING NODE: spot_mini State Machine
process[spot_teleop-3]: started with pid [17181]
process[spot_pybullet-4]: started with pid [17186]
/usr/bin/env: ‘python’: No such file or directory
[ INFO] [1623770031.203788747]: STARTING NODE: Teleoperation
[spot_pybullet-4] process has died [pid 17186, exit code 127, cmd /home/jon/catkin_ws/src/spot_mini_mini/mini_ros/src/spot_pybullet_interface __name:=spot_pybullet __log:=/home/jon/.ros/log/4d0e42a6-cde7-11eb-8559-f11a37245d28/spot_pybullet-4.log].
log file: /home/jon/.ros/log/4d0e42a6-cde7-11eb-8559-f11a37245d28/spot_pybullet-4*.log
[ WARN] [1623770031.228110980]: Couldn't set gain on joystick force feedback: Bad file descriptor

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by JonathanMortes** [comment]
Same happens with spot_real.launch:

on@jon-noetic:~/catkin_ws$ roslaunch mini_ros spot_real.launch 
... logging to /home/jon/.ros/log/4d0e42a6-cde7-11eb-8559-f11a37245d28/roslaunch-jon-noetic-30900.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://jon-noetic:36887/

SUMMARY
========

PARAMETERS
 * /BaseClearanceHeight: 0.035
 * /BasePenetrationDepth: 0.003
 * /BaseStepVelocity: 0.001
 * /CD_SCALE: 0.05
 * /CHPD_SCALE: 0.0005
 * /ClearanceHeight_LIMITS: [0.0, 0.04]
 * /PenetrationDepth_LIMITS: [0.0, 0.02]
 * /RESIDUALS_SCALE: 0.015
 * /RPY_SCALE: 0.785
 * /SLV_SCALE: 0.05
 * /STEPLENGTH_SCALE: 0.05
 * /SV_SCALE: 0.05
 * /SwingPeriod_LIMITS: [0.1, 0.3]
 * /Tswing: 0.2
 * /YAW_SCALE: 1.25
 * /Z_SCALE: 0.035
 * /Z_SCALE_CTRL: 0.15
 * /actions_to_filter: 14
 * /agent_num: 0
 * /alpha: 0.7
 * /com_offset: 0.0
 * /dt: 0.001
 * /elbow_length: 0.10652
 * /foot_x: 0.23
 * /foot_y: 0.185
 * /height: 0.2
 * /hip_x: 0.23
 * /hip_y: 0.075
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /serial_node/baud: 500000
 * /serial_node/port: /dev/ttyS0
 * /shoulder_length: 0.055
 * /spot_joy/deadzone: 0.005
 * /spot_joy/dev: /dev/input/js0
 * /spot_sm/frequency: 200.0
 * /spot_teleop/axis_angular: 0
 * /spot_teleop/axis_linear_x: 4
 * /spot_teleop/axis_linear_y: 3
 * /spot_teleop/axis_linear_z: 1
 * /spot_teleop/button_estop: 1
 * /spot_teleop/button_switch: 0
 * /spot_teleop/frequency: 200.0
 * /spot_teleop/scale_angular: 1.0
 * /spot_teleop/scale_linear: 1.0
 * /wrist_length: 0.145

NODES
  /
    serial_node (rosserial_python/serial_node.py)
    spot_joy (joy/joy_node)
    spot_real (mini_ros/spot_real_interface)
    spot_sm (mini_ros/spot_sm)
    spot_teleop (mini_ros/teleop_node)

ROS_MASTER_URI=http://localhost:11311

process[spot_sm-1]: started with pid [30914]
process[spot_joy-2]: started with pid [30915]
[ INFO] [1623772430.923082346]: STARTING NODE: spot_mini State Machine
process[spot_teleop-3]: started with pid [30916]
[ INFO] [1623772430.930437359]: STARTING NODE: Teleoperation
process[spot_real-4]: started with pid [30921]
/usr/bin/env: ‘python’: No such file or directory
process[serial_node-5]: started with pid [30927]
[ERROR] [1623772430.943202662]: Couldn't open joystick /dev/input/js0. Will retry every second.
[spot_real-4] process has died [pid 30921, exit code 127, cmd /home/jon/catkin_ws/src/mini_ros/src/spot_real_interface __name:=spot_real __log:=/home/jon/.ros/log/4d0e42a6-cde7-11eb-8559-f11a37245d28/spot_real-4.log].
log file: /home/jon/.ros/log/4d0e42a6-cde7-11eb-8559-f11a37245d28/spot_real-4*.log
[ERROR] [1623772431.267400, 0.000000]: Error opening serial: [Errno 13] could not open port /dev/ttyS0: [Errno 13] Permission denied: '/dev/ttyS0'
[ERROR] [1623772434.272595, 0.000000]: Error opening serial: [Errno 13] could not open port /dev/ttyS0: [Errno 13] Permission denied: '/dev/ttyS0'
[ERROR] [1623772437.279337, 0.000000]: Error opening serial: [Errno 13] could not open port /dev/ttyS0: [Errno 13] Permission denied: '/dev/ttyS0'
[ERROR] [1623772440.286008, 0.000000]: Error opening serial: [Errno 13] could not open port /dev/ttyS0: [Errno 13] Permission denied: '/dev/ttyS0'
[ERROR] [1623772443.292706, 0.000000]: Error opening serial: [Errno 13] could not open port /dev/ttyS0: [Errno 13] Permission denied: '/dev/ttyS0'
^C[serial_node-5] killing on exit
[spot_teleop-3] killing on exit
[spot_sm-1] killing on exit
[spot_joy-2] killing on exit
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyS0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rosserial_python/SerialClient.py", line 374, in __init__
    self.port = Serial(port, baud, timeout=self.timeout, write_timeout=10)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyS0: [Errno 13] Permission denied: '/dev/ttyS0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 572, in signal_shutdown
    h()
  File "/opt/ros/noetic/lib/python3/dist-packages/rosserial_python/SerialClient.py", line 354, in shutdown
    self.txStopRequest()
  File "/opt/ros/noetic/lib/python3/dist-packages/rosserial_python/SerialClient.py", line 422, in txStopRequest
    self.port.flushInput()
AttributeError: 'SerialClient' object has no attribute 'port'
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by JonathanMortes** [comment]
Fixed it by changing first line to: 
#!/usr/bin/env python3
